Import https://downloads.isc.org/isc/bind9/9.18.41/bind-9.18.41.tar.xz

diff --git a/bind/util/check-make-install.sh.in b/bind/util/check-make-install.sh.in
--- a/bind/util/check-make-install.sh.in
+++ b/bind/util/check-make-install.sh.in
@@ -18,44 +18,44 @@ includedir=@includedir@
 install_dir="${DESTDIR}@prefix@"
 
 headers_to_install() {
-	find "${abs_top_srcdir}/lib" -name "*.h" -or -name "*.h.in" |
-		sed -n \
-		    -e "s|\.h\.in$|\.h|" \
-		    -e "s|.*include/|${DESTDIR}${includedir}/|p" |
-		sort -u
+  find "${abs_top_srcdir}/lib" -name "*.h" -or -name "*.h.in" \
+    | sed -n \
+      -e "s|\.h\.in$|\.h|" \
+      -e "s|.*include/|${DESTDIR}${includedir}/|p" \
+    | sort -u
 }
 
 status=0
 
 for header in $(headers_to_install); do
-	if [ ! -f "${header}" ]; then
-		echo "Missing $header"
-		status=1
-	fi
+  if [ ! -f "${header}" ]; then
+    echo "Missing $header"
+    status=1
+  fi
 done
 
 named_binary_path="${install_dir}/sbin/named"
 if [ ! -x "${named_binary_path}" ]; then
-	echo "ERROR: ${named_binary_path} does not exist or is not executable"
-	status=1
+  echo "ERROR: ${named_binary_path} does not exist or is not executable"
+  status=1
 fi
 
 named_man_page_path="${install_dir}/share/man/man8/named.8"
 if [ ! -f "${named_man_page_path}" ]; then
-	echo "ERROR: ${named_man_page_path} does not exist"
-	status=1
+  echo "ERROR: ${named_man_page_path} does not exist"
+  status=1
 fi
 
 if [ -n "${DESTDIR}" ]; then
-	for expected_subdir in bin etc include lib sbin share; do
-		echo "${install_dir}/${expected_subdir}" >> "${abs_builddir}/expected_dirs"
-	done
-	find "${install_dir}" -maxdepth 1 -mindepth 1 -type d | sort > "${abs_builddir}/existing_dirs"
-	if ! diff -u "${abs_builddir}/expected_dirs" "${abs_builddir}/existing_dirs"; then
-		echo "ERROR: Contents of DESTDIR do not match expectations"
-		status=1
-	fi
-	rm -f "${abs_builddir}/expected_dirs" "${abs_builddir}/existing_dirs"
+  for expected_subdir in bin etc include lib sbin share; do
+    echo "${install_dir}/${expected_subdir}" >>"${abs_builddir}/expected_dirs"
+  done
+  find "${install_dir}" -maxdepth 1 -mindepth 1 -type d | sort >"${abs_builddir}/existing_dirs"
+  if ! diff -u "${abs_builddir}/expected_dirs" "${abs_builddir}/existing_dirs"; then
+    echo "ERROR: Contents of DESTDIR do not match expectations"
+    status=1
+  fi
+  rm -f "${abs_builddir}/expected_dirs" "${abs_builddir}/existing_dirs"
 fi
 
 exit $status
